### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [78]:
import numpy as np
import random

In [79]:
#1.1a
vector_1 = np.array([random.uniform(0, 1) for _ in range(10)])
print(vector_1)
vector_1.shape

[0.17891547 0.70349799 0.24883576 0.75767597 0.19529561 0.47433177
 0.19184363 0.19294486 0.58298259 0.20798072]


(10,)

In [82]:
#1.1b
vector_2 = np.random.rand(10)
print(vector_2)
vector_2.shape

[0.16710755 0.98349863 0.16992706 0.95071631 0.8119663  0.42698226
 0.28045886 0.75650672 0.47182684 0.10745349]


(10,)

In [83]:
#1.2a
matrix_1=np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

print(matrix_1)
rows, cols = matrix_1.shape
print(f"Matrix size: {rows} x {cols}")

[[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix size: 3 x 3


In [84]:
#1.2b
matrix_2 = np.random.rand(3, 3)
print(matrix_2)
matrix_2.shape

[[0.25605672 0.16308767 0.35966309]
 [0.3388675  0.55462787 0.2412378 ]
 [0.02253833 0.92013955 0.28055006]]


(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [85]:
# 2.1
vector_1_1=(vector_1+10).round(2)
vector_1_1

array([10.18, 10.7 , 10.25, 10.76, 10.2 , 10.47, 10.19, 10.19, 10.58,
       10.21])

In [86]:
#2.2
matrix_1_2 = matrix_1*2
matrix_1_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [87]:
#2.3
vector_1_3=vector_1**2
print(vector_1_3)
print(vector_1)

[0.03201075 0.49490943 0.06191924 0.57407288 0.03814037 0.22499063
 0.03680398 0.03722772 0.3398687  0.04325598]
[0.17891547 0.70349799 0.24883576 0.75767597 0.19529561 0.47433177
 0.19184363 0.19294486 0.58298259 0.20798072]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [88]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [89]:
#3.1
result_matrix =np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [90]:
#3.2
# 2x2 * 2x1 = 2x1
#   0.5202
#   0.2846
display(np.dot(result_matrix, C))

array([[0.5202],
       [0.2846]])

In [91]:
#3.3
# 2x2 * 2x2 = 2x2
#   0.5202 0.7281
#   0.2846 0.2034
display(np.dot(result_matrix, D))

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [92]:
#4.1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [93]:
#4.2
display(vector_1.T)
print(vector_1.shape)
print(vector_1.T.shape)

array([0.17891547, 0.70349799, 0.24883576, 0.75767597, 0.19529561,
       0.47433177, 0.19184363, 0.19294486, 0.58298259, 0.20798072])

(10,)
(10,)


In [98]:
#4.3
column_vector =np.expand_dims(vector_1, axis=1)
print(column_vector)
column_vector.shape

[[0.17891547]
 [0.70349799]
 [0.24883576]
 [0.75767597]
 [0.19529561]
 [0.47433177]
 [0.19184363]
 [0.19294486]
 [0.58298259]
 [0.20798072]]


(10, 1)

In [99]:
column_vector_1 =vector_1.reshape(-1,1)
print(column_vector_1)
column_vector_1.shape

[[0.17891547]
 [0.70349799]
 [0.24883576]
 [0.75767597]
 [0.19529561]
 [0.47433177]
 [0.19184363]
 [0.19294486]
 [0.58298259]
 [0.20798072]]


(10, 1)

In [96]:
#4.4
column_vector_t=column_vector.T
display(column_vector_t)
column_vector_t.shape

array([[0.17891547, 0.70349799, 0.24883576, 0.75767597, 0.19529561,
        0.47433177, 0.19184363, 0.19294486, 0.58298259, 0.20798072]])

(1, 10)

In [100]:
column_vector_t_2=column_vector.reshape(1,-1)
display(column_vector_t_2)
column_vector_t_2.shape

array([[0.17891547, 0.70349799, 0.24883576, 0.75767597, 0.19529561,
        0.47433177, 0.19184363, 0.19294486, 0.58298259, 0.20798072]])

(1, 10)