**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [2]:
import numpy as np

In [86]:
array_1=np.array ([5, 15, 25, 35, 45])
array_2=np.zeros(7)
array_3=np.ones(6)
array_4=np.arange (10,20)

print(array_1)
print(array_2)
print(array_3)
print(array_4)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [87]:
array_5=np.array ([12, 24, 36, 48, 60])


print(array_5 * 2)
print(array_5 + 10)
print(array_5 ** 2)
print(array_5 ** 0.5) # квадратний корінь з усіх елементів
print(np.sqrt(array_5)) # квадратний корінь з усіх елементів

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [89]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

print(f"Середнє значення елементів: {data.mean()}")
print(f"Середнє значення елементів: {np.mean(data)}")
print()

print(f"Мінімальний елемент: {data.min()}")
print(f"Мінімальний елемент: {np.min(data)}")
print()

print(f"Максимальний елемент: {data.max()}")
print(f"Максимальний елемент: {np.max(data)}")
print()

print(f"Суму всіх елементів: {data.sum()}")
print(f"Суму всіх елементів: {np.sum(data)}")


Середнє значення елементів: 45.42857142857143
Середнє значення елементів: 45.42857142857143

Мінімальний елемент: 18
Мінімальний елемент: 18

Максимальний елемент: 79
Максимальний елемент: 79

Суму всіх елементів: 318
Суму всіх елементів: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [90]:
arr=np.array([15, 22, 35, 44, 58, 67])

print(arr[0])
print(arr[-1])
print(arr[0:3])
print(arr[arr>40])

15
67
[15 22 35]
[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [91]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [92]:
print(matrix.shape)

print(matrix[0,])

print(matrix[:,1])

print(np.sum(matrix))

print(matrix.mean())

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
